[package]
name = "mident"
version = "0.0.1"
edition = "2024"
license = "0BSD"
repository = "https://github.com/ArcaneNibble/mident"
description = "Macro Identifier toolbox -- generate/concat idents in macros"

[lib]
proc-macro = true

[dependencies]
uuid = { version = "1.16", features = ["v4"] }
